### ISSUE TITLE
BUG: 文件路径包含空格时，会报错。

### ISSUE THREAD

**Issue by fslongjin** [DragonOS-Community/NovaShell#13]
![image](https://github.com/DragonOS-Community/NovaShell/assets/63215266/a4d588b2-422a-4760-b1f2-f5a181825cb2)

如题，我这个目录名称有空格，shell会把它当参数来处理，导致无法cd进去

**Comment by MemoryShore** [comment]
我修改了一下，现在用引号包裹带空格的参数可以正常处理
