### ISSUE TITLE
Feat: 使用Command重构cmd_exec

### ISSUE THREAD

**Issue by yuyi2439** [DragonOS-Community/NovaShell#36]
目前已经可以在DragonOS中使用Command来创建并管理子进程
当前使用sys_fork系统调用来创建子进程，不便于向子进程设置环境变量，且代码较混乱

其余需求：
使用形如`exec xxx &`的命令来创建后台进程的时候，`&`会被当做一个参数，需要改正

**Comment by fslongjin** [comment]
因为主线安装了core utils,貌似在另外一个PR里面，nova shell要删掉exec命令。你可以确认一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月24日(周日) 晚上11:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [DragonOS-Community/NovaShell] Feat: 使用Command重构cmd_exec (Issue #36)




 
目前已经可以在DragonOS中使用Command来创建并管理子进程
 当前使用sys_fork系统调用来创建子进程，不便于向子进程设置环境变量，且代码较混乱
 
其余需求：
 使用形如exec xxx &amp;的命令来创建后台进程的时候，&amp;会被当做一个参数，需要改正

**Comment by yuyi2439** [comment]
> 因为主线安装了core utils,貌似在另外一个PR里面，nova shell要删掉exec命令。你可以确认一下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月24日(周日) 晚上11:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [DragonOS-Community/NovaShell] Feat: 使用Command重构cmd_exec (Issue #36) 目前已经可以在DragonOS中使用Command来创建并管理子进程 当前使用sys_fork系统调用来创建子进程，不便于向子进程设置环境变量，且代码较混乱 其余需求： 使用形如exec xxx &amp;的命令来创建后台进程的时候，&amp;会被当做一个参数，需要改正 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;



> 因为主线安装了core utils,貌似在另外一个PR里面，nova shell要删掉exec命令。你可以确认一下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月24日(周日) 晚上11:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [DragonOS-Community/NovaShell] Feat: 使用Command重构cmd_exec (Issue #36) 目前已经可以在DragonOS中使用Command来创建并管理子进程 当前使用sys_fork系统调用来创建子进程，不便于向子进程设置环境变量，且代码较混乱 其余需求： 使用形如exec xxx &amp;的命令来创建后台进程的时候，&amp;会被当做一个参数，需要改正 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

并没有删掉exec，exec是shell内置的指令

**Comment by yuyi2439** [comment]
并没有删掉exec，exec是shell内置的指令

**Comment by MemoryShore** [comment]
https://github.com/DragonOS-Community/NovaShell/pull/42
